### ISSUE TITLE
Incompatable with babili 

### ISSUE THREAD

**Issue by jawline** [azu/babel-plugin-strip-function-call#1]
Crashes when used in conjunction with babili

TypeError: src/SymbolicExecution.js: Property alternate of ConditionalExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-types/lib/index.js:511:9)
    at NodePath._replaceWith (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath._remove (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-traverse/lib/path/removal.js:58:10)
    at NodePath.remove (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-traverse/lib/path/removal.js:30:8)
    at PluginPass.CallExpression (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-plugin-strip-function-call/lib/babel-plugin-strip-function-call.js:21:26)
    at newFn (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/pbai002/ExpoSE/ExpoSE/Analyser/node_modules/babel-traverse/lib/path/context.js:105:12)

**Comment by azu** [comment]
Thanks for report!
Can you create minimum reproduce code and `.babelrc`?
